name: screenshot_detect_plugin_flutter
description: A simple package to detect user screenshots and get path images for Android and IOS.
version: 1.0.6
homepage: https://github.com/tvanhuu/screenshot_detect_plugin_flutter

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:

flutter:
  plugin:
    platforms:
      android:
        package: com.dev.huutv.screenshot_detect_plugin_flutter
        pluginClass: ScreenshotDetectPluginFlutterPlugin
      ios:
        pluginClass: ScreenshotDetectPluginFlutterPlugin
